#!/bin/bash
#hostname=${var.Node1Hostname}
dnsdomain=${var.dns_domain}
primarynameserver=169.254.169.253
ntpserver=169.254.169.123
username=iseadmin
password=${var.password}
timezone=${var.time_zone}
ersapi=${var.ers_api}
openapi=${var.open_api}
pxGrid=${var.px_grid}
pxgrid_cloud=${var.px_grid_cloud}
